### ISSUE TITLE
Choosing a long date range on the Coolify UI make the container crash (504)

### ISSUE THREAD

**Issue by MatteoGauthier** [coollabsio/sentinel#5]
Just after changing the select to "30 days" range my server crashed...

![SCR-20240710-ogjc](https://github.com/coollabsio/sentinel/assets/32040951/163d41fa-db8f-4ff3-b3a4-45a4abb8eb05)

**Comment by Thijmen** [comment]
Same here, I guess it's due to the fact that Coolify stores it as CSV. Perhaps a timebased database is a better fit?

**Comment by andrasbacsai** [comment]
In coolify v312, I disabled Sentinel on all servers until this bug (and a few others) are not fixed.

**Comment by andrasbacsai** [comment]
I changed everything in the next version (rewritten from 0), so this won't be an issue (also closing this).
